name: React CodePipeline

on:
  push:
    branches: ['dev']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build-Deploy:
    uses: xxjt123xx/pipeline-templates/.github/workflows/react-on-github-pages.yml@main
